In [3]:
import numpy as np

In [4]:
L = np.random.random(100)

In [5]:
L

array([0.05155024, 0.8929462 , 0.5070818 , 0.5176918 , 0.91512872,
       0.73272053, 0.90222444, 0.93284299, 0.15443072, 0.90891302,
       0.89075178, 0.46999398, 0.64877615, 0.41096608, 0.23466895,
       0.22229165, 0.3120437 , 0.78034762, 0.68495681, 0.26151341,
       0.32548345, 0.8830234 , 0.29682463, 0.20878661, 0.77256412,
       0.00792514, 0.08261577, 0.18573725, 0.47881401, 0.72542518,
       0.38666742, 0.33448776, 0.20521986, 0.50085173, 0.33911466,
       0.2701137 , 0.01793811, 0.04765576, 0.73985276, 0.92388827,
       0.14765903, 0.94093848, 0.55256703, 0.20268624, 0.52561929,
       0.50458601, 0.77637551, 0.17960446, 0.70004746, 0.56376976,
       0.4840422 , 0.64200724, 0.49106782, 0.12211295, 0.47244505,
       0.39913583, 0.5365275 , 0.17414187, 0.99104819, 0.01234325,
       0.13651692, 0.28694574, 0.53442426, 0.77593184, 0.64963855,
       0.24318084, 0.71563576, 0.1027365 , 0.44263789, 0.89551533,
       0.69766066, 0.12112145, 0.76836214, 0.98077044, 0.36692

In [6]:
np.sum(L)

48.89061991170379

In [7]:
A = np.arange(16).reshape(4, -1)

In [8]:
A.sum()

120

In [9]:
np.sum(A, axis = 0)

array([24, 28, 32, 36])

In [10]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.sum(A, axis = 1)

array([ 6, 22, 38, 54])

In [13]:
np.prod(A + 1)

2004189184

In [14]:
np.mean(A)

7.5

In [15]:
np.median(A)

7.5

In [17]:
M = np.random.random(1000).reshape(100, -1)

In [18]:
np.mean(M)

0.503210036442357

In [20]:
np.percentile(M, q=50)

0.5097097953421934

In [23]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(M, q=percent))

0.00013890989290332723
0.24016264770531054
0.5097097953421934
0.7608877300752527
0.9995351253437338


In [24]:
np.std(M)

0.29456184347814074

In [25]:
np.var(M)

0.0867666796332407

In [27]:
N = np.random.normal(0, 1, size=100000)

In [28]:
np.std(N)

1.0008742422868135

In [29]:
np.mean(N)

-0.005888685016697663

### 索引

In [30]:
M

array([[4.69215972e-01, 9.64011764e-02, 8.37541285e-01, 2.57215339e-01,
        4.08906260e-01, 3.17114750e-01, 4.76122142e-01, 8.17017421e-01,
        5.96350834e-01, 3.75353082e-01],
       [3.12013446e-01, 2.50484293e-01, 4.57083555e-01, 3.03623724e-02,
        4.16157436e-01, 9.80218344e-01, 2.40269099e-01, 2.30711084e-01,
        6.89149406e-01, 5.58623093e-01],
       [4.90712382e-01, 9.70830006e-01, 9.57131292e-01, 7.99321817e-01,
        8.96451130e-01, 3.31354646e-02, 8.38391845e-01, 1.59828150e-01,
        2.78951853e-01, 5.39996744e-02],
       [6.25359841e-01, 9.11709017e-01, 8.76773505e-01, 8.05212492e-01,
        4.80921614e-01, 2.90124909e-01, 2.43742988e-02, 5.21480695e-01,
        4.30512958e-01, 6.53715747e-01],
       [6.40828963e-01, 9.32517870e-01, 2.98742762e-01, 8.77747117e-01,
        5.84064437e-01, 9.73787817e-01, 1.29170734e-01, 8.83515692e-01,
        9.20764244e-01, 3.30960470e-01],
       [9.87096165e-01, 1.70126822e-01, 8.63594394e-01, 4.36475313e-01,
   

In [34]:
S = np.arange(16)

In [35]:
S

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
np.random.shuffle(S)

In [37]:
S

array([14,  7,  1, 10,  4, 12, 15,  0,  3,  9,  6, 13,  5,  8, 11,  2])

In [38]:
np.argsort(S)

array([ 7,  2, 15,  8,  4, 12, 10,  1, 13,  9,  3, 14,  5, 11,  0,  6],
      dtype=int64)

In [39]:
np.argmin(S)

7

In [40]:
np.argmax(S)

6

In [41]:
np.partition(S, 3)

array([ 1,  0,  2,  3,  4,  5,  9,  7,  8,  6, 10, 13, 15, 12, 11, 14])

In [48]:
R = np.random.randint(10, size=(4, 4))

In [44]:
np.sort(R)

array([[0, 1, 4, 6],
       [0, 3, 4, 6],
       [1, 3, 7, 8],
       [2, 3, 3, 5]])

In [45]:
np.sort(R, axis=1)

array([[0, 1, 4, 6],
       [0, 3, 4, 6],
       [1, 3, 7, 8],
       [2, 3, 3, 5]])

In [46]:
np.sort(R, axis=0)

array([[3, 0, 1, 0],
       [3, 1, 2, 3],
       [6, 3, 4, 5],
       [6, 8, 4, 7]])

In [47]:
np.argsort(R, axis=0)

array([[2, 1, 2, 0],
       [3, 0, 3, 1],
       [0, 3, 0, 3],
       [1, 2, 1, 2]], dtype=int64)

In [49]:
R

array([[6, 4, 6, 9],
       [6, 7, 3, 7],
       [9, 8, 0, 1],
       [9, 4, 2, 6]])

In [50]:
R

array([[6, 4, 6, 9],
       [6, 7, 3, 7],
       [9, 8, 0, 1],
       [9, 4, 2, 6]])

In [51]:
np.sort(R)

array([[4, 6, 6, 9],
       [3, 6, 7, 7],
       [0, 1, 8, 9],
       [2, 4, 6, 9]])

In [52]:
np.argsort(R)

array([[1, 0, 2, 3],
       [2, 0, 1, 3],
       [2, 3, 1, 0],
       [2, 1, 3, 0]], dtype=int64)

In [53]:
np.sort(R, axis=0)

array([[6, 4, 0, 1],
       [6, 4, 2, 6],
       [9, 7, 3, 7],
       [9, 8, 6, 9]])

In [54]:
R

array([[6, 4, 6, 9],
       [6, 7, 3, 7],
       [9, 8, 0, 1],
       [9, 4, 2, 6]])

In [55]:
np.argsort(R, axis=0)

array([[0, 0, 2, 2],
       [1, 3, 3, 3],
       [2, 1, 1, 1],
       [3, 2, 0, 0]], dtype=int64)

In [70]:
np.partition(R, 4, axis=1)

ValueError: kth(=4) out of bounds (4)

In [79]:
X = np.arange(20, 36)
np.random.shuffle(X)

In [80]:
X

array([33, 31, 29, 23, 20, 32, 26, 35, 25, 21, 34, 22, 28, 30, 27, 24])

In [88]:
np.partition(X, 10)

array([25, 26, 22, 23, 20, 27, 24, 21, 28, 29, 30, 31, 32, 33, 34, 35])

In [89]:
np.argpartition(X, 10)

array([ 8,  6, 11,  3,  4, 14, 15,  9, 12,  2, 13,  1,  5,  0, 10,  7],
      dtype=int64)