In [1]:
import numpy as np

In [2]:
A = np.arange(4).reshape(2, 2)

In [3]:
A

array([[0, 1],
       [2, 3]])

In [4]:
B = np.full((2, 2), 1)

In [5]:
B

array([[1, 1],
       [1, 1]])

In [6]:
A.dot(B)

array([[1, 1],
       [5, 5]])

In [7]:
A + B

array([[1, 2],
       [3, 4]])

In [8]:
A.T

array([[0, 2],
       [1, 3]])

In [9]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [10]:
A1 = np.linalg.inv(A)

In [11]:
A.dot(A1)

array([[1., 0.],
       [0., 1.]])

In [12]:
C = np.arange(10).reshape(2, -1)

In [13]:
C1 = np.linalg.inv(C)

LinAlgError: Last 2 dimensions of the array must be square

In [14]:
C2 = np.linalg.pinv(C)

In [15]:
C2

array([[-3.20000000e-01,  1.20000000e-01],
       [-1.80000000e-01,  8.00000000e-02],
       [-4.00000000e-02,  4.00000000e-02],
       [ 1.00000000e-01, -1.28275056e-17],
       [ 2.40000000e-01, -4.00000000e-02]])

In [16]:
C.dot(C2)

array([[ 1.00000000e+00, -8.32667268e-17],
       [ 5.82867088e-16,  1.00000000e+00]])

In [17]:
%%time
C.dot(C2)

Wall time: 0 ns


array([[ 1.00000000e+00, -8.32667268e-17],
       [ 5.82867088e-16,  1.00000000e+00]])