In [1]:
import numpy as np

In [2]:
A = np.arange(4).reshape(2, 2)

In [3]:
A

array([[0, 1],
       [2, 3]])

In [4]:
B = np.full((2, 2), 1)

In [5]:
B

array([[1, 1],
       [1, 1]])

In [6]:
A.dot(B)

array([[1, 1],
       [5, 5]])

In [7]:
A + B

array([[1, 2],
       [3, 4]])

In [8]:
A.T

array([[0, 2],
       [1, 3]])

In [9]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [10]:
A1 = np.linalg.inv(A)

In [11]:
A.dot(A1)

array([[1., 0.],
       [0., 1.]])

In [12]:
C = np.arange(10).reshape(2, -1)

In [13]:
C1 = np.linalg.inv(C)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
C2 = np.linalg.pinv(C)

In [ ]:
C2

In [ ]:
C.dot(C2)

In [ ]:
%%time
C.dot(C2)

In [18]:
x1 = np.array([1,2,3,4]).reshape(1,-1)
x2 = np.array([1,2,3,4]).reshape(1, -1)

In [19]:
x1

array([[1, 2, 3, 4]])

In [20]:
x2

array([[1, 2, 3, 4]])

In [21]:
x1.dot(x2)

ValueError: shapes (1,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [22]:
X = np.array([1,2,3,4]).reshape(-1, 1)

In [23]:
X

array([[1],
       [2],
       [3],
       [4]])

In [24]:
X.shape

(4, 1)

In [26]:
X_b = np.hstack([np.ones((4, 1)), X])

In [27]:
X_b

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.]])

In [28]:
X_b.shape

(4, 2)

In [36]:
theta = np.ones(X_b.shape[1])

In [37]:
theta

array([1., 1.])

In [38]:
X_b.dot(theta)

array([2., 3., 4., 5.])

In [39]:
theta.shape

(2,)

In [40]:
X_b.dot(theta).shape

(4,)

In [42]:
X_b.dot(theta).dot(X_b[:, 1])

40.0