In [1]:
import sklearn.datasets as datasets
import matplotlib.pyplot as plt

In [2]:
boston = datasets.load_boston()
X = boston.data
y = boston.target
X = X[y < 50]
y = y[y < 50]
X.shape

(490, 13)

In [3]:
from playML.LinearRegression import LinearRegression
from playML.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
X_train, y_train, X_test, y_test = train_test_split(X, y, seed=666)

In [5]:
std = StandardScaler()
std.fit(X_train)
X_train_standard = std.transform(X_train)
X_test_standard = std.transform(X_test)

In [6]:
reg = LinearRegression()
%time reg.fit_small_gd(X_train_standard, y_train, n_iters=5, k=10)
reg.score(X_test_standard, y_test)

Wall time: 2.99 ms


0.8087212925922214

In [7]:
reg.coef_

array([-7.25816200e-01,  3.21672026e-01,  5.70170678e-02,  1.78291225e-03,
       -9.84698317e-01,  2.60006123e+00, -6.65386270e-01, -1.66725704e+00,
        1.00540701e+00, -1.23598383e+00, -1.80024040e+00,  7.27544095e-01,
       -2.58026296e+00])

In [8]:
reg = LinearRegression()
%time reg.fit_sgd(X_train_standard, y_train, n_iters=5)
reg.score(X_test_standard, y_test)

Wall time: 9.97 ms


0.8118522976717831

In [9]:
reg.coef_

array([-1.02966022,  0.89091004,  0.14625817,  0.11019586, -1.53556039,
        2.21698049, -0.43254401, -2.37756015,  2.93368232, -2.96189176,
       -1.85464074,  0.71397364, -2.8773872 ])

In [10]:
from sklearn.linear_model import SGDRegressor

In [11]:
reg = SGDRegressor(max_iter=5)
reg.fit(X_train_standard, y_train)
reg.score(X_test_standard, y_test)

C:\Users\zlm31\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDRegressor in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.80495051238564

In [12]:
import numpy as np

In [13]:
X = np.arange(16).reshape(4, -1)

In [14]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.random.seed(666)

In [16]:
index = np.random.permutation(len(X))

In [17]:
X_new = X[index]

In [18]:
X_new

array([[12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [19]:
X_new = X[index,:]

In [20]:
X_new

array([[12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])